server:
  port: 0
  
spring:
  application:
    name: 'email'
  profiles:
    active: default
  rabbitmq:
    host: 127.0.0.1
    password: suop
    username: suop
    virtual-host: /suop
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      