server:
  port: 5555
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"
        
#spring:
#  rabbitmq:
#    host: 127.0.0.1
#    password: suop
#    username: suop
#    virtual-host: /suop