server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/betobadran/suop-config/
          search-paths: common-data, mail, gw